### ISSUE TITLE
Error while installing otel launcher dependency

### ISSUE THREAD

**Issue by kasattejaswi** [lightstep/otel-launcher-go#107]
I was running ```go get 'github.com/lightstep/otel-launcher-go/launcher'``` for getting dependencies but getting the following error:

```
github.com/lightstep/otel-launcher-go/launcher imports
        go.opentelemetry.io/otel/sdk/metric/controller/basic imports
        go.opentelemetry.io/otel/metric/registry: cannot find module providing package go.opentelemetry.io/otel/metric/registry
```
I tried deleting the created folders in gopath and tried reinstalling the older versions but still getting the same output.

**Comment by PirateRoc** [comment]
Same problem here

**Comment by drewthor** [comment]
Until a new version is released, or you check out the latest version of this repo via `go get -u github.com/lightstep/otel-launcher-go@main`, this package requires you to use an older open telemetry version. The released version of this package uses open telemetry go version 0.18.0 for example.

In order to fix this you will need to downgrade the version of `go.opentelemetry.io/otel` and other packages that rely on it to v0.18.0

**Comment by codeboten** [comment]
Published a new tag. Please confirmed if it resolved the issue for you.

**Comment by kasattejaswi** [comment]
Still facing the error. Sharing trace.
```
go get 'github.com/lightstep/otel-launcher-go/launcher'
go: finding github.com/lightstep/otel-launcher-go v1.5.0
go: downloading github.com/lightstep/otel-launcher-go v1.5.0
go: extracting github.com/lightstep/otel-launcher-go v1.5.0
go: finding go.opentelemetry.io/otel v1.5.0
go: downloading go.opentelemetry.io/otel v1.5.0
go: extracting go.opentelemetry.io/otel v1.5.0
go: downloading go.opentelemetry.io/otel/sdk v1.5.0
go: downloading go.opentelemetry.io/otel/trace v1.5.0
go: downloading github.com/sethvargo/go-envconfig v0.5.0
go: downloading github.com/lightstep/otel-launcher-go/pipelines v0.0.0-20220106234948-aab622036bba
go: extracting go.opentelemetry.io/otel/trace v1.5.0
go: extracting github.com/sethvargo/go-envconfig v0.5.0
go: extracting github.com/lightstep/otel-launcher-go/pipelines v0.0.0-20220106234948-aab622036bba
go: extracting go.opentelemetry.io/otel/sdk v1.5.0
go: finding github.com/lightstep/otel-launcher-go/pipelines v0.0.0-20220106234948-aab622036bba
go: finding go.opentelemetry.io/otel/sdk v1.5.0
go: finding go.opentelemetry.io/otel/trace v1.5.0
/home/tejaswi/go/pkg/mod/go.opentelemetry.io/otel/sdk/metric@v0.23.0/controller/basic/controller.go:25:2: module go.opentelemetry.io/otel/metric@latest found (v0.27.0), but does not contain package go.opentelemetry.io/otel/metric/registry
```

**Comment by codeboten** [comment]
Thanks for following up @kasattejaswi and apologies for not fixing the issue w/ the previous release. The pipelines module has now been tagged as well and the dependency updated. I was able to reproduce the issue with 1.5.0. Please confirm `v1.5.1` fixes the issue for you.

**Comment by kasattejaswi** [comment]
This updated fixed the issue @codeboten
Thanks for the help.
