### ISSUE TITLE
launcher.WithResourceAttributes is not adding the attribute properly

### ISSUE THREAD

**Issue by mingh2** [lightstep/otel-launcher-go#163]
**Describe the bug**
Instead of adding the key value pair from ResourceAttributes map, it always use the host name key.
https://github.com/lightstep/otel-launcher-go/blob/main/launcher/config.go#L314

This behavior is unexpected and different from the java implementation. 
https://github.com/lightstep/otel-launcher-java/blob/main/common/src/main/java/com/lightstep/opentelemetry/common/VariablesConverter.java#L124

**To Reproduce**
1. Create a launcher using launcher.WithResourceAttributes 
2. Run some operations that create traces and spans
3. Navigate to the lightstep dashboard and the attributes won't be attached to the span

**Expected behavior**
Expect the attributes passed into the launcher.WithResourceAttributes will be attached to span

**Additional context**

**Comment by mingh2** [comment]
On the other hand, setting `OTEL_RESOURCE_ATTRIBUTES` env variables work as expected.

**Comment by jmacd** [comment]
@mingh2 That was really embarrassing, sorry!

**Comment by mingh2** [comment]
No worries, thanks for the quick fix!

**Comment by chrisghill** [comment]
@jmacd Is this for sure working in v1.5.2? I've updated my dependencies and confirmed I'm on v1.5.2. From my go.mod:

```
module foo

go 1.17

require (
...
	github.com/lightstep/otel-launcher-go v1.5.2
...
)
```

and my main.go

```
	// Setup Tracing
	if os.Getenv("LS_ACCESS_TOKEN") != "" {
		otelLauncher := launcher.ConfigureOpentelemetry(
			launcher.WithServiceName("foo"),
			launcher.WithAccessToken(os.Getenv("LS_ACCESS_TOKEN")),
			launcher.WithResourceAttributes(map[string]string{
				"foo":   "bar",
                                "hello": "world",
			}),
		)
		defer otelLauncher.Shutdown()
	}
	_, span := otel.Tracer("foo").Start(context.Background(), "TestingAttributes")
	defer span.End()
```

These spans are showing up in Lightstep but have no attributes.

![image](https://user-images.githubusercontent.com/15616541/175607159-337c8267-f61e-4198-9996-d5a1652cf509.png)

**Comment by chrisghill** [comment]
Following up here:

I had a misunderstanding between service attributes and span attributes.  You can disregard my previous comment.
