### ISSUE TITLE
unknown revision pipelines/v1.5.2 - error when trying to go get latest version

### ISSUE THREAD

**Issue by jklq** [lightstep/otel-launcher-go#167]
**Describe the bug**
I tried to run `go get github.com/lightstep/otel-launcher-go/launcher`, but I got back this error message:
```
go: github.com/lightstep/otel-launcher-go@v1.5.2 requires
        github.com/lightstep/otel-launcher-go/pipelines@v1.5.2: reading github.com/lightstep/otel-launcher-go/pipelines/pipelines/go.mod at revision pipelines/v1.5.2: unknown revision pipelines/v1.5.2
```
This might be because of a version mismatch?
Downloading the 1.5.1 version worked completely fine for me.

**To Reproduce**
I managed to reproduce it in to separate go projects on my machine. I simply ran `go get github.com/lightstep/otel-launcher-go/launcher`.

There might just be some environmental variables on my side that makes this problem occur.

**Expected behavior**
The package installs normally without problems.

**Additional context**

**Comment by codeboten** [comment]
Thanks for reporting this @jklq, a `1.5.2` tag was just pushed for the `pipelines` package, please try again and confirm this is working for you.

**Comment by jklq** [comment]
Sorry for the late response. Yes, it is working now.
