### ISSUE TITLE
ConfigureOpentelemetry results in compilation errors

### ISSUE THREAD

**Issue by NasAmin** [lightstep/otel-launcher-go#335]
**Describe the bug**
Using the metric example, I am getting compile time errors.

**To Reproduce**
Use the metric example like this:

```go
defer launcher.ConfigureOpentelemetry().Shutdown()
```

**Expected behavior**
Expect the program to compile successfully.

**Additional context**
Getting an error like this:

```
github.com/lightstep/otel-launcher-go/lightstep/sdk/metric/internal/viewstate
../../../go/pkg/mod/github.com/lightstep/otel-launcher-go/lightstep/sdk/metric@v1.11.1/internal/viewstate/collectors.go:108:16: internal compiler error: method ToNumber on struct {} not found
```

This also happens if you build this repository locally!

**Comment by jmacd** [comment]
This was an issue with the Go compiler. Please update to the latest Go 1.19 or 1.20 compiler.
