### ISSUE TITLE
Depending on  otel v1.12.0 causes compiler errors

### ISSUE THREAD

**Issue by tullo** [lightstep/otel-launcher-go#367]
**Describe the bug**
I'm getting a wall of compiler errors when trying to build with `go build` .

**To Reproduce**
Have a `go 1.19` `go.mod` file and depend on both `launcher` and `otel` with version `v1.12.0`

Launch with:
```go
otel := launcher.ConfigureOpentelemetry(
  launcher.WithServiceName("fib-workshop"),
  launcher.WithAccessToken("access-token"),
)
return otel
```

**Expected behavior**
Compiles and runs without issues.

**Additional context**
See stacktrace

[stacktrace.txt](https://github.com/lightstep/otel-launcher-go/files/10609694/stacktrace.txt)

**Comment by jmacd** [comment]
This library has (because of history) become one minor version ahead of OTel. This library's 1.12.x corresponds with OTel-Go 1.11.x and metrics v0.34.x. I will be publishing a v1.13.x of this library to match OTel v1.12.x and v1.13.x.
