### ISSUE TITLE
OTEL_RESOURCE_LABELS is now supported in opentelemetry-go, can drop launcher support?

### ISSUE THREAD

**Issue by tobert** [lightstep/otel-launcher-go#55]
I was looking at the launcher source code and noticed this line, went to look at the issue it mentions and it says it was closed last year. I forget about these things all the time so I thought I'd drop an issue so y'all can take care of it.

https://github.com/lightstep/otel-launcher-go/blob/103307c0a081428d537027bf42c088a4012817da/launcher/config.go#L294

https://github.com/open-telemetry/opentelemetry-go/pull/1042

**Comment by codeboten** [comment]
Thanks for opening this issue @tobert!
